In [1]:
import numpy as np


In [35]:
x=np.array([2,4,6,5,7])

In [36]:
print(x)

[2 4 6 5 7]


In [9]:
type(x)

numpy.ndarray

In [14]:
x=np.array(([2,4,6,5,7]),dtype="float")

In [15]:
type(x)

numpy.ndarray

In [16]:
x=np.zeros((3,4))

In [17]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
x=np.ones((3,4))

In [19]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
x=np.full((3,4),7)

In [21]:
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [22]:
x=np.eye(3,3)

In [23]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x=np.arange(2,4,3)

In [31]:
print(x)

[2]


In [33]:
x=np.linspace(4,10,10)

In [34]:
print(x)

[ 4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.        ]
