In [1]:
import numpy as np

In [4]:
x=np.array([[2,3,4,5],[34,6,10,6],[12,43,9,3]])

In [5]:
print(x)

[[ 2  3  4  5]
 [34  6 10  6]
 [12 43  9  3]]


In [6]:

print("value at [0][0] and [0][1] : ",x[0:1,0:2])

value at [0][0] and [0][1] :  [[2 3]]


In [7]:
print("value at[0][1] , [0][2] , [0][3] :",x[0:1,1:4])

value at[0][1] , [0][2] , [0][3] : [[3 4 5]]


In [8]:
print("value at[1][0] :",x[1:2, 0:2])

value at[1][0] : [[34  6]]


In [9]:
print("value at[1][1],[1,2],[1,3] :",x[1:5,1:4])

value at[1][1],[1,2],[1,3] : [[ 6 10  6]
 [43  9  3]]


In [10]:
print(x[1:3,1:4])

[[ 6 10  6]
 [43  9  3]]


In [11]:
y=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])

In [12]:
print(y)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [13]:
print("value as 35,36,43,47:",y[1:3,1:3])
     

value as 35,36,43,47: [[35 36]
 [43 47]]


In [14]:

print(y[2: ,3: ])

[[50]
 [53]]


In [15]:
print(y[0:6 ,2: ])

[[24 25]
 [36 40]
 [47 50]
 [52 53]]
